### ISSUE TITLE
Hi team, I see details about retention but don't see reference to archiving capability (or lack there of in the documentation) in BTP DMS. Request to add some context around archiving in BTP DMS. Thanks.

### ISSUE THREAD

**Issue by iamashokkumar** [SAP-docs/btp-document-management-service#3]
### Issue description

Hi team, I see details about retention but don't see reference to archiving capability (or lack there of in the documentation) in BTP DMS. Request to add some context around archiving in BTP DMS. Thanks.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Retention

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/document-management-service/sap-document-management-service/retention

**Comment by Vikramkulkarni01** [comment]
Hi Ashok, 

Thanks for sharing this feedback. 

We've received this query and looking into it. We'll keep you posted with an update as soon as we hear from the concerned team. 

We truly appreciate your patience and support. 

Regards, 
Vikram Kulkarni.

**Comment by Vikramkulkarni01** [comment]
Hi @iamashokkumar, 

Regarding your concern, I checked and found that by default we do not have the archiving option at BTP DMS but you can use the repository as an archiving repository via the secondary type provided by CMIS and also supported by BTP DMS i.e. the Retention feature. 

By enabling it you can retain the document and then upon expiry and deleted date set on the document will get deleted from the repository.

Hence no documentation update is required at this point. I hope this satisfies your concern. 

Please feel free to reach out to us if there are any further concerns.

Regards, 
Vikram Kulkarni.
